### ISSUE TITLE
Implement user input checks

### ISSUE THREAD

**Issue by ppicha** [ReliSA/SPADe-Web-GUI#5]
Validate that the proper values have been set as AP parameters. If not, display a prompt and highlight the incorrectly set value. Both in individual AP detail and overall configuration page.

Checks need to consider:
- regular expressions for String values (decide on the separator first)
- integer vs. real numerical value
- can the value of a numerical field be zero? can it be negative? (for both integer and real values)
- percentage (0 - 100 real value)

**Comment by OndrejVane** [comment]
Time estimate: 6h

**Comment by OndrejVane** [comment]
![Snímek obrazovky 2021-08-15 v 23 05 30](https://user-images.githubusercontent.com/36737582/129492881-c2c1721e-9259-4c78-92f9-be22e643a3dc.png)

**Comment by OndrejVane** [comment]
- created new data types for validations
- - Percentage (0-100)
- - Positive Integer (0 - infinity)
- - Positive Float (0.0 - infinity)
- all configuration values ​​are checked, if they are not entered correctly, the user is notified by an error message
